<a href="https://colab.research.google.com/github/milindtheengineer/learn-d2l/blob/main/linearalgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.tensor(3.0)
y = torch.tensor(4.0)

In [3]:
x + y, x * y, x/y

(tensor(7.), tensor(12.), tensor(0.7500))

In [23]:
x = torch.arange(3, dtype=torch.float32)
x

tensor([0., 1., 2.])

In [5]:
len(x)

3

In [6]:
x.shape

torch.Size([3])

In [8]:
A = torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [9]:
A.T


tensor([[0, 2, 4],
        [1, 3, 5]])

In [11]:
torch.arange(24).reshape(2, 4, 3)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]])

In [14]:
A = torch.arange(6, dtype=torch.float32).reshape(2,3)
B = A.clone()
A+B

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])

In [15]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [16]:
a = 2
a + A

tensor([[2., 3., 4.],
        [5., 6., 7.]])

In [17]:
(a * A).shape

torch.Size([2, 3])

In [18]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [20]:
A.mean(), A.mean(axis=0), A.mean(axis=1)

(tensor(2.5000), tensor([1.5000, 2.5000, 3.5000]), tensor([1., 4.]))

In [21]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [24]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [25]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

In [26]:
B = torch.ones(3, 4)
torch.mm(A, B), A@B


(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

In [27]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)


tensor(5.)

In [28]:
torch.abs(u).sum()

tensor(7.)